name: Build C++ Application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat

    - name: Install libcurl
      run: |
        cd vcpkg
        .\vcpkg install curl --triplet=x64-windows

    - name: Add vcpkg to path
      run: |
        echo "##[add-path]$(pwd)/vcpkg"

    - name: Build the application
      run: |
        g++ main.cpp -o ZcashDownloader.exe -I"%cd%\vcpkg\installed\x64-windows\include" -L"%cd%\vcpkg\installed\x64-windows\lib" -lcurl

    - name: Run the application
      run: |
        .\ZcashDownloader.exe
