name: Cross-Platform Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev build-essential

    - name: Compile
      run: |
        g++ -std=c++17 -o zcash-downloader main.cpp -lcurl -lstdc++fs

    - name: Run
      run: ./zcash-downloader

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: zcash-downloader

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install curl
      run: |
        $curlUrl = "https://curl.se/windows/dl-8.6.0_3/curl-8.6.0_3-win64-mingw.zip"
        Invoke-WebRequest -Uri $curlUrl -OutFile curl.zip
        Expand-Archive -Path curl.zip -DestinationPath C:\curl
        echo "CURL_ROOT=C:\curl\curl-8.6.0_3-win64-mingw" >> $env:GITHUB_ENV

    - name: Compile
      run: |
        cl /EHsc /I "$env:CURL_ROOT\include" /Fe: zcash-downloader.exe main.cpp "$env:CURL_ROOT\lib\libcurl.lib"

    - name: Copy DLL
      run: |
        copy "$env:CURL_ROOT\bin\libcurl-x64.dll" libcurl.dll

    - name: Run
      run: |
        .\zcash-downloader.exe

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: |
          zcash-downloader.exe
          libcurl.dll
