name: Cross-Platform Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev build-essential

    - name: Compile
      run: |
        g++ -std=c++17 -o zcash-downloader main.cpp -lcurl -lstdc++fs

    - name: Run
      run: ./zcash-downloader

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: zcash-downloader

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install curl -y --version=8.6.0

    - name: Compile
      run: |
        cl /EHsc /I "C:\tools\curl\include" /Fe: zcash-downloader.exe main.cpp "C:\tools\curl\lib\libcurl.lib"

    - name: Add curl DLL to PATH
      run: |
        $env:PATH += ";C:\tools\curl\bin"
        echo "PATH=$env:PATH" >> $env:GITHUB_ENV

    - name: Run
      run: |
        .\zcash-downloader.exe

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: |
          zcash-downloader.exe
          C:\tools\curl\bin\libcurl.dll
