name: Build C++ Application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Build Tools
      run: |
        choco install mingw

    - name: Build the application
      run: |
        g++ main.cpp -o ZcashDownloader.exe -lcurl

    - name: Run the application
      run: |
        .\ZcashDownloader.exe
